[package]
name = "softconnet"
version = "0.1.0"
description = "Manage symbolic links around a single source of truth"
edition = "2021"

[lib]
name = "softconnet_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
walkdir = "2"

[dev-dependencies]
tempfile = "3"
